// Paper Signal style: the archive stays compact and editorial; long-form evidence remains server-side on article routes.
export type InsightIndexItem = {
  slug: string;
  index: string;
  title: string;
  excerpt: string;
  category: string;
  tags: string[];
  readTime: string;
  date: string;
  stat: string;
  statLabel: string;
};

export const insightIndex: InsightIndexItem[] = [
  { slug: "custom-storefront-vs-hosted-platform", index: "01", title: "A custom storefront is not anti-Shopify. It is a decision about control.", excerpt: "Hosted commerce is excellent infrastructure. The case for custom is what happens above it: the speed, story, discovery, and buying experience your brand can own.", category: "Strategy", tags: ["Custom Commerce", "Shopify", "Strategy"], readTime: "9 min", date: "2026 / 01", stat: "Target / sub-500ms", statLabel: "edge-cached page-load ambition from the product brief" },
  { slug: "why-3d-product-previews-earn-their-bandwidth", index: "02", title: "Why 3D previews are useful when the product has something to explain.", excerpt: "A good product visualizer does not exist to impress a visitor. It reduces uncertainty around shape, scale, material, configuration, or fit before the cart is involved.", category: "Product Experience", tags: ["3D / AR", "Product UX", "Conversion"], readTime: "7 min", date: "2026 / 02", stat: "More interactions", statLabel: "Google says 3D/AR products often receive more interactions than 2D-only products" },
  { slug: "why-an-ai-shopping-assistant-is-good", index: "03", title: "Why an AI shopping assistant is good when it shortens a decision.", excerpt: "The useful chatbot is not a floating mascot. It understands a shopper’s context, keeps the catalog honest, and hands the person back to a product page with better next steps.", category: "AI Commerce", tags: ["AI", "Chatbot", "Product Discovery"], readTime: "8 min", date: "2026 / 03", stat: "Capability, not theatre", statLabel: "Google documents AI-powered search and recommendations for websites and apps" },
  { slug: "why-ai-advanced-search-is-good", index: "04", title: "Why advanced AI search is good before it is clever.", excerpt: "Better search is not only vector embeddings. It is tolerant input, useful autocomplete, understandable filters, merchandising rules, and a result page that knows what the shopper meant.", category: "AI Commerce", tags: ["AI Search", "Semantic Search", "UX"], readTime: "8 min", date: "2026 / 04", stat: "31 guidelines", statLabel: "Baymard condensed search findings from testing 19 leading ecommerce sites" },
  { slug: "cart-recovery-that-respects-intent", index: "05", title: "Cart recovery works better when it respects intent.", excerpt: "An abandoned cart is not a permission slip to shout. Recovery should answer why the shopper paused, remove friction, and stop when the person has made a choice.", category: "Growth Systems", tags: ["Recovery", "Lifecycle", "Checkout"], readTime: "7 min", date: "2026 / 05", stat: "70.19%", statLabel: "Baymard’s tracked global average cart-abandonment rate" },
  { slug: "newsletter-and-lifecycle-email", index: "06", title: "A newsletter is useful when it behaves like a relationship, not a broadcast.", excerpt: "Email earns attention when it helps people decide, return, learn, or maintain a product. The list is an owned channel only when the value is clear and consent is respected.", category: "Growth Systems", tags: ["Newsletter", "Email", "Retention"], readTime: "7 min", date: "2026 / 06", stat: "$36 : $1", statLabel: "Litmus average email-marketing ROI benchmark" },
  { slug: "seo-for-commerce-that-compounds", index: "07", title: "SEO for ecommerce is a product system, not a metadata sprint.", excerpt: "Search visibility compounds when product data, page architecture, performance, internal linking, structured data, and useful editorial content agree with each other.", category: "Performance & SEO", tags: ["SEO", "Next.js", "Technical SEO"], readTime: "10 min", date: "2026 / 07", stat: "3 phases", statLabel: "Google describes Search processing as crawling, rendering, and indexing" },
  { slug: "ecommerce-strategy-before-the-redesign", index: "08", title: "The ecommerce strategy is the part that tells the build what not to do.", excerpt: "Good strategy turns a list of features into a sequence of decisions: who is buying, what uncertainty blocks them, and which system change creates the most leverage first.", category: "Strategy", tags: ["Strategy", "UX", "Operations"], readTime: "8 min", date: "2026 / 08", stat: "32 improvements", statLabel: "Baymard says the average site has 32 unique checkout improvements available" },
  { slug: "reviews-comments-and-earned-trust", index: "09", title: "Reviews and comments are useful when the system earns the trust they display.", excerpt: "Social proof is not a wall of praise. It is verified context, honest variation, visible answers, and a moderation system that lets a brand learn from criticism.", category: "Trust & Content", tags: ["Reviews", "Comments", "Trust"], readTime: "8 min", date: "2026 / 09", stat: "+270%", statLabel: "Northwestern reports higher purchase likelihood with five reviews versus none in its study" },
  { slug: "ai-workspace-vision-for-product-fit", index: "10", title: "AI workspace vision is good when it helps a shopper imagine the fit.", excerpt: "A room-photo assistant can make product discovery more personal, but the output should be guidance with evidence—not a confident hallucination about someone’s home.", category: "AI Commerce", tags: ["AI", "Vision", "Personalization"], readTime: "6 min", date: "2026 / 10", stat: "Input → context", statLabel: "A room photo can turn a generic catalog question into a context-aware shortlist" },
  { slug: "the-operating-system-behind-a-better-store", index: "11", title: "The best ecommerce features also make the business easier to run.", excerpt: "Inventory history, tax, fulfillment, campaign tooling, sentiment alerts, and daily strategy briefs are not back-office extras. They determine how quickly the storefront can stay true.", category: "Operations", tags: ["Operations", "Inventory", "AI"], readTime: "8 min", date: "2026 / 11", stat: "One ledger", statLabel: "Every RESTOCK, SALE, and RETURN should be explainable in the inventory history" },
  { slug: "global-commerce-without-global-confusion", index: "12", title: "Global commerce is a clarity problem before it is a translation problem.", excerpt: "Language, currency, tax, delivery, and support must agree on every route. A second language that still shows the wrong tax model is not localization; it is new friction.", category: "Commerce Systems", tags: ["Localization", "Tax", "International"], readTime: "6 min", date: "2026 / 12", stat: "2 additional languages", statLabel: "A manageable first step for full-UI localization in the supplied system brief" },
];

export const insightTopics = ["All", "Strategy", "AI Commerce", "3D / AR", "Growth Systems", "Performance & SEO", "Trust & Content", "Operations", "Commerce Systems"] as const;
