// Paper Signal style: editorial scale, warm paper, charcoal ink, signal orange, asymmetrical proof-led layouts.
import { useMemo, useState } from "react";
import { Link, useLocation, useRoute } from "wouter";
import { ArrowDownRight, ArrowUpRight, Check, ChevronDown, Menu, X } from "lucide-react";
import { toast } from "sonner";

const IMG = {
  hero: "/manus-storage/paper-signal-hero_ff979c14.png",
  work1: "/manus-storage/selected-work-01_898ca8d2.png",
  work2: "/manus-storage/selected-work-02_0d61cfec.png",
  work3: "/manus-storage/selected-work-03_ba04d09f.png",
  mark: "/manus-storage/cs-monogram_f5dfdf45.png",
};

const projects = [
  { slug: "form-and-function", number: "01", title: "Form & Function", category: "E-commerce / Furniture", description: "A modular furniture storefront concept built around browsing by room, material, and intent.", stack: "Next.js · Shopify · TypeScript", scope: "Selected experiment", image: IMG.work1, tags: ["E-commerce", "Experiments"] },
  { slug: "signal-search", number: "02", title: "Signal Search", category: "AI / Beauty", description: "A product discovery system that turns natural language into a shorter path to the right routine.", stack: "Next.js · AI · Semantic search", scope: "Selected experiment", image: IMG.work2, tags: ["AI", "E-commerce"] },
  { slug: "in-your-space", number: "03", title: "In Your Space", category: "3D / AR / Product", description: "An immersive product page concept where configuration and context do the selling.", stack: "React · Three.js · WebGL", scope: "Selected experiment", image: IMG.work3, tags: ["3D / AR", "Experiments"] },
];

const services = [
  ["01", "Custom E-commerce", "Storefronts that make product, story, and checkout feel like one system.", ["Next.js storefronts", "Shopify & headless integrations", "Product, collection & account flows", "Payments, inventory & analytics"], "Method / map the commerce model before the component model."],
  ["02", "AI Commerce", "Useful AI in the places it can remove friction—not as a decorative chatbot.", ["Semantic product search", "Shopping assistants", "Recommendations & discovery", "Content and workflow automation"], "Constraint / AI should shorten a decision, not add another interface."],
  ["03", "3D & AR Experiences", "Make a product easier to understand by letting people see, shape, and place it.", ["Interactive 3D", "Product configurators", "WebGL product moments", "AR-ready experience design"], "Deliverable / a lightweight product moment that earns its bandwidth."],
  ["04", "Conversion & Recovery", "A better storefront is only useful when it helps more people finish the journey.", ["Abandoned cart recovery", "Checkout optimization", "Upsells & cross-sells", "Analytics-led UX improvements"], "System note / build → launch → improve, with the handoff still open."],
  ["05", "Performance & SEO", "The invisible work that makes a store feel fast, discoverable, and dependable.", ["Core Web Vitals", "Technical SEO", "Image and rendering optimization", "Structured data and caching"], "Proof cue / performance is designed into the route, not audited at the end."],
  ["06", "Ongoing Development", "Build, launch, improve—without disappearing after the handoff.", ["Feature development", "Maintenance & bug fixes", "Growth experiments", "Analytics-driven improvements"], "Working style / direct access to the person making the next decision."],
] as const;

function Header() {
  const [open, setOpen] = useState(false);
  const [loc] = useLocation();
  const links = [["Work", "/work"], ["Services", "/services"], ["About", "/about"], ["Insights", "/insights"]];
  return <header className="site-header">
    <Link href="/" className="brand" onClick={() => setOpen(false)}><span className="mark-lockup"><img src={IMG.mark} alt="" /><b>CS/</b></span><span>commerce<br />studio</span></Link>
    <nav className="desktop-nav">{links.map(([label, href]) => <Link key={href} href={href} className={loc.startsWith(href) ? "active" : ""}>{label}</Link>)}<Link href="/contact" className="nav-cta">Start a project <ArrowUpRight size={15} /></Link></nav>
    <button className="mobile-toggle" aria-label="Toggle navigation" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button>
    {open && <div className="mobile-nav">{links.map(([label, href]) => <Link key={href} href={href} onClick={() => setOpen(false)}>{label}</Link>)}<Link href="/contact" onClick={() => setOpen(false)} className="nav-cta">Start a project <ArrowUpRight size={15} /></Link></div>}
  </header>;
}

function Footer() { return <footer className="footer"><div className="footer-top"><div><div className="eyebrow"><span className="signal-dot" /> Independent commerce engineering</div><h2>Make the next<br /><em>move</em> useful.</h2></div><Link href="/contact" className="circle-cta">Start<br />a project <ArrowUpRight /></Link></div><div className="footer-bottom"><div className="brand footer-brand"><span className="mark-lockup"><img src={IMG.mark} alt="" /><b>CS/</b></span><span>commerce<br />studio</span></div><div className="footer-links"><Link href="/work">Work</Link><Link href="/services">Services</Link><Link href="/about">About</Link><Link href="/insights">Insights</Link><Link href="/contact">Contact</Link></div><div className="footer-meta"><a href="mailto:hello@commercestudio.dev">hello@commercestudio.dev</a><span>© 2026 Commerce Studio</span></div></div></footer> }

function SectionLabel({ children, index }: { children: React.ReactNode; index?: string }) { return <div className="section-label"><span>{index || ""}</span><span>{children}</span><span className="label-line" /></div> }

function WorkCard({ project, featured = false }: { project: typeof projects[number]; featured?: boolean }) { return <Link href={`/work/${project.slug}`} className={`work-card ${featured ? "featured" : ""}`}><div className="work-image"><img src={project.image} alt="" /><span className="work-arrow"><ArrowUpRight /></span></div><div className="work-card-meta"><div><span className="project-number">{project.number}</span><h3>{project.title}</h3><p>{project.category}</p></div><div className="work-detail"><span>{project.stack}</span><span>{project.scope}</span></div></div></Link> }

function Hero() { return <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="signal-dot" /> Next-generation commerce systems</div><h1>Build a store<br />people <em>remember.</em></h1><p>Custom Next.js storefronts, useful AI, and immersive product experiences—built with the care of a studio and the overhead of one person.</p><div className="hero-actions"><Link className="button button-dark" href="/contact">Start a project <ArrowUpRight size={16} /></Link><a className="text-link" href="#work">See the work <ArrowDownRight size={16} /></a></div></div><div className="hero-visual"><img src={IMG.hero} alt="Abstract product composition in warm paper and orange" /><div className="hero-stamp">CS<br /><span>01—26</span></div><div className="hero-caption">Directly designed<br />and developed.</div></div></section> }

function TrustStrip() { return <div className="trust-strip">{["Custom-built", "Next.js", "AI-ready", "3D / AR", "Performance-first", "Direct communication"].map((item, i) => <span key={item}><b>{String(i + 1).padStart(2, "0")}</b>{item}</span>)}</div> }

function ServicesPreview() { const [active, setActive] = useState(0); return <section className="services-preview section-pad"><div className="section-intro"><SectionLabel index="02">What I build</SectionLabel><h2>Commerce is<br /><em>more</em> than a cart.</h2><p>The best storefronts do two jobs at once: they make a product desirable, then make buying it feel obvious.</p><Link href="/services" className="text-link">Explore all services <ArrowUpRight size={16} /></Link></div><div className="service-list">{services.slice(0, 5).map(([number, title, desc, bullets], i) => <div className={`service-row ${active === i ? "open" : ""}`} key={number}><button onClick={() => setActive(active === i ? -1 : i)}><span className="service-num">{number}</span><span className="service-title">{title}</span><span className="service-plus">{active === i ? "—" : "+"}</span></button>{active === i && <div className="service-detail"><p>{desc}</p><ul>{bullets.slice(0, 3).map(b => <li key={b}>{b}</li>)}</ul></div>}</div>)}</div></section> }

function Demo() { const [color, setColor] = useState("orange"); const [size, setSize] = useState("M"); const colors: Record<string, string> = { orange: "#ff5a1f", stone: "#d8d1c4", ink: "#252525" }; return <section className="demo-section"><div className="demo-copy"><SectionLabel index="03">A small proof of concept</SectionLabel><h2>The site should<br /><em>do the talking.</em></h2><p>Here’s a tiny commerce interaction: choose a finish, select a size, and add the object to your cart. No theatre. Just a useful product moment.</p><span className="demo-note"><span className="signal-dot" /> Selected experiment · interactive product card</span></div><div className="product-card"><div className="product-art" style={{ "--product": colors[color] } as React.CSSProperties}><div className="product-shape" /><span className="product-code">OBJ—001</span></div><div className="product-info"><div><span className="eyebrow">The everyday object</span><h3>Signal form / 01</h3></div><strong>$148</strong></div><div className="swatches"><span>Finish</span>{Object.keys(colors).map(c => <button key={c} aria-label={c} className={color === c ? "selected" : ""} style={{ background: colors[c] }} onClick={() => setColor(c)} />)}</div><div className="sizes"><span>Size</span>{["S", "M", "L"].map(s => <button key={s} className={size === s ? "selected" : ""} onClick={() => setSize(s)}>{s}</button>)}</div><button className="button button-orange" onClick={() => toast.success(`Signal form / 01 — ${size} added to cart`)}>Add to cart <ArrowUpRight size={16} /></button></div></section> }

function Home() { return <><Hero /><TrustStrip /><main><section className="work-section section-pad" id="work"><div className="section-intro row-intro"><SectionLabel index="01">Selected work</SectionLabel><div><h2>Ideas that<br /><em>ship.</em></h2><p>Self-initiated experiments and builds exploring what commerce can feel like when design and engineering start in the same room.</p></div><Link href="/work" className="text-link">View all work <ArrowUpRight size={16} /></Link></div><div className="work-grid"><WorkCard project={projects[0]} featured /><WorkCard project={projects[1]} /><WorkCard project={projects[2]} /></div></section><ServicesPreview /><section className="split-statement"><div className="split-image"><img src={IMG.work3} alt="Abstract product form" /></div><div className="split-copy"><SectionLabel index="04">Why this studio</SectionLabel><h2>Big-agency<br /><em>thinking.</em><br />Small-studio<br /><em>economics.</em></h2><p>You work directly with the person shaping the strategy, designing the experience, and shipping the system. Fewer layers. Better context. A more sensible budget.</p><Link href="/about" className="text-link">How I work <ArrowUpRight size={16} /></Link></div></section><Demo /><FAQ /><CTA /></main></> }

function FAQ() { const qs = ["How much does a custom store cost?", "Do you work with Shopify?", "Can you improve an existing store?", "What happens after launch?"]; const [open, setOpen] = useState<number | null>(null); const answers = ["Projects are scoped around the problem, not a fixed template. Starting ranges are shared once the scope is clear, and pricing stays transparent from there.", "Yes. Shopify can be the commerce engine behind a custom Next.js storefront, or the existing theme can be improved in place.", "Yes. Performance, UX, recovery, and technical SEO work can be more valuable than starting over.", "Build → launch → improve. Ongoing development and optimization are available when there is a clear next problem to solve."]; return <section className="faq section-pad"><div className="faq-heading"><SectionLabel index="05">Useful answers</SectionLabel><h2>Before we<br /><em>start.</em></h2></div><div className="faq-list">{qs.map((q, i) => <div className="faq-item" key={q}><button onClick={() => setOpen(open === i ? null : i)}><span>{q}</span>{open === i ? <ChevronDown className="rotate" /> : <ChevronDown />}</button>{open === i && <p>{answers[i]}</p>}</div>)}</div></section> }

function CTA() { return <section className="closing-cta"><div className="eyebrow"><span className="signal-dot" /> The next useful thing</div><h2>Bring the hard part.<br /><em>I’ll bring the system.</em></h2><Link href="/contact" className="button button-paper">Start a project <ArrowUpRight size={16} /></Link></section> }

function WorkPage() { const [filter, setFilter] = useState("All"); const filters = ["All", "E-commerce", "AI", "3D / AR", "Experiments"]; const filtered = useMemo(() => filter === "All" ? projects : projects.filter(p => p.tags.includes(filter)), [filter]); return <main className="inner-page"><div className="inner-hero"><SectionLabel index="01">Selected work</SectionLabel><h1>Proof, not<br /><em>promises.</em></h1><p>Self-initiated concepts and selected builds. Every project here is labeled honestly, with the technology and scope in plain sight.</p></div><div className="filter-row">{filters.map(f => <button className={filter === f ? "active" : ""} key={f} onClick={() => setFilter(f)}>{f}</button>)}</div><div className="work-page-grid">{filtered.map(p => <WorkCard key={p.slug} project={p} featured />)}</div><CTA /></main> }

function ServicesPage() { return <main className="inner-page services-page"><div className="inner-hero"><SectionLabel index="02">Services</SectionLabel><h1>Commerce,<br /><em>properly made.</em></h1><p>From a sharper storefront to a smarter recovery loop, each service is designed to move a real business forward.</p></div><div className="long-services">{services.map(([number, title, desc, bullets, proof]) => <article key={number}><div className="service-num">{number}</div><div><h2>{title}</h2><p>{desc}</p><div className="service-proof">{proof}</div><ul>{bullets.slice(0, 4).map(b => <li key={b}><Check size={15} />{b}</li>)}</ul></div><ArrowUpRight className="article-arrow" /></article>)}</div><CTA /></main> }

function AboutPage() { return <main className="inner-page about-page"><div className="inner-hero"><SectionLabel index="03">About the studio</SectionLabel><h1>Small by design.<br /><em>Serious by default.</em></h1><p>Commerce Studio is an independent practice for brands that need senior thinking, modern engineering, and a direct line to the person doing the work.</p></div><div className="about-story"><div><span className="story-year">01 / The premise</span><h2>Good commerce<br />makes complexity<br /><em>feel simple.</em></h2></div><div><p>I work across strategy, design, and development because the seams between them are where most storefronts lose their edge.</p><p>No invented team. No layers of account management. Just a focused practice with the right tools, a bias toward clarity, and a preference for shipping useful things.</p><p>The studio is intentionally lean, which keeps the work close, the feedback loop short, and the budget sensible without making the result feel reduced.</p></div></div><div className="principles"><SectionLabel index="04">What to expect</SectionLabel>{["Direct communication", "Technical curiosity", "Clear scope", "Useful motion", "Honest proof"].map((x, i) => <div key={x}><span>0{i + 1}</span><strong>{x}</strong><ArrowUpRight size={17} /></div>)}</div><CTA /></main> }

function InsightsPage() { const articles = ["Why headless commerce is a UX decision, not a status symbol", "The practical case for AI-assisted product discovery", "What to fix before you rebuild your storefront", "3D product experiences that earn their bandwidth"]; return <main className="inner-page insights-page"><div className="inner-hero"><SectionLabel index="05">Insights</SectionLabel><h1>Useful notes<br />for <em>better commerce.</em></h1><p>Field notes on Next.js, Shopify, AI search, performance, recovery, and the small decisions that compound into a better store.</p></div><div className="article-list">{articles.map((a, i) => <article key={a}><span>2026 / 0{i + 1}</span><h2>{a}</h2><p>Coming soon · a practical note from the studio</p><ArrowUpRight /></article>)}</div><div className="newsletter"><div><span className="eyebrow"><span className="signal-dot" /> One useful note, occasionally</span><h2>No noise.<br /><em>Just signal.</em></h2></div><div><p>Join the small list for practical commerce thinking, not a weekly content treadmill.</p><form onSubmit={(e) => { e.preventDefault(); toast.success("You’re on the list. Thank you."); }}><input required type="email" placeholder="Your email address" aria-label="Your email address" /><button type="submit"><ArrowUpRight /></button></form></div></div></main> }

function ContactPage() { const [sent, setSent] = useState(false); if (sent) return <main className="inner-page contact-page"><div className="success-state"><span className="signal-dot" /><h1>Good.<br /><em>Let’s make it useful.</em></h1><p>Your project note is captured in this demo flow. In a live build, this is where it would move into a direct email or CRM workflow.</p><Link href="/" className="button button-dark">Back home <ArrowUpRight size={16} /></Link></div></main>; return <main className="inner-page contact-page"><div className="inner-hero"><SectionLabel index="06">Start a project</SectionLabel><h1>Have a project<br /><em>in mind?</em></h1><p>Tell me what you’re building, what isn’t working, or what you’d like to improve. I’ll reply with a clear next step.</p></div><form className="project-form" onSubmit={(e) => { e.preventDefault(); setSent(true); }}><div className="form-grid"><label>Name<input required placeholder="Your name" /></label><label>Email<input required type="email" placeholder="you@brand.com" /></label><label>Company / brand<input placeholder="Brand name" /></label><label>Website<input placeholder="https://" /></label></div><label>What do you need?<select defaultValue=""><option value="" disabled>Select a focus</option><option>New e-commerce store</option><option>Existing store improvement</option><option>AI integration</option><option>3D / AR</option><option>Cart recovery</option><option>Performance / SEO</option><option>Custom web application</option></select></label><div className="form-grid"><label>Budget range<select defaultValue=""><option value="" disabled>Choose a range</option><option>Under $5k</option><option>$5k—$10k</option><option>$10k—$20k</option><option>$20k+</option><option>Not sure yet</option></select></label><label>Timeline<select defaultValue=""><option value="" disabled>Choose a timeline</option><option>ASAP</option><option>1—2 months</option><option>3—6 months</option><option>Flexible</option></select></label></div><label>Project description<textarea required placeholder="What are you trying to make happen?" rows={6} /></label><button className="button button-dark" type="submit">Send project note <ArrowUpRight size={16} /></button></form><div className="prefer-email"><span>Prefer email?</span><a href="mailto:hello@commercestudio.dev">hello@commercestudio.dev <ArrowUpRight size={14} /></a></div></main> }

function CaseStudy({ slug }: { slug: string }) { const project = projects.find(p => p.slug === slug) || projects[0]; return <main className="case-page"><div className="case-hero"><Link href="/work" className="back-link">← Back to work</Link><div><span className="project-number">{project.number}</span><h1>{project.title}<br /><em>{project.category.split(" / ")[0]}</em></h1><p>{project.description}</p></div></div><img className="case-image" src={project.image} alt="" /><div className="case-meta"><div><span>Project type</span><strong>{project.scope}</strong></div><div><span>Stack</span><strong>{project.stack}</strong></div><div><span>Focus</span><strong>UX · Systems · Motion</strong></div></div><div className="case-body"><SectionLabel index="01">The build</SectionLabel><h2>Make the product<br /><em>easier to choose.</em></h2><div><p>This selected experiment explores how a commerce experience can create confidence before checkout. The product story is structured around intent, useful filters, and a clear visual rhythm that keeps the interface feeling premium without getting in the way.</p><p>It is presented as a concept, not a client case study. The outcome is the working interaction, the system thinking, and the performance-minded direction—not an invented business result.</p></div></div><CTA /></main> }

export default function Site() { const [loc] = useLocation(); const [, params] = useRoute("/work/:slug"); return <div className="app-shell"><Header />{loc === "/" ? <Home /> : loc === "/work" ? <WorkPage /> : loc === "/services" ? <ServicesPage /> : loc === "/about" ? <AboutPage /> : loc === "/insights" ? <InsightsPage /> : loc === "/contact" ? <ContactPage /> : params?.slug ? <CaseStudy slug={params.slug} /> : <Home />}<Footer /></div> }
