export const siteImages = {
  hero: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663885080823/ZEXKXwKOALbgthhi.webp",
  work1: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663885080823/XsZZDReMXkzYJqct.webp",
  work2: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663885080823/CXgTkRaWpKBdfqDu.webp",
  work3: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663885080823/JKZekIgRdrtXLoNW.webp",
  mark: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663885080823/iORsRQmAyqEwbyOe.webp",
} as const;

export const projects = [
  {
    slug: "form-and-function",
    number: "01",
    title: "Form & Function",
    category: "Furniture",
    industry: "Furniture",
    service: "Custom E-commerce",
    description: "A modular furniture storefront concept built around browsing by room, material, and intent.",
    stack: "Next.js · Shopify · TypeScript",
    scope: "Selected experiment",
    image: siteImages.work1,
    gallery: [siteImages.work1, siteImages.hero, siteImages.work2],
  },
  {
    slug: "signal-search",
    number: "02",
    title: "Signal Search",
    category: "Beauty",
    industry: "Beauty",
    service: "AI Commerce",
    description: "A product discovery system that turns natural language into a shorter path to the right routine.",
    stack: "Next.js · AI · Semantic search",
    scope: "Selected experiment",
    image: siteImages.work2,
    gallery: [siteImages.work2, siteImages.hero, siteImages.work1],
  },
  {
    slug: "in-your-space",
    number: "03",
    title: "In Your Space",
    category: "Product",
    industry: "Product",
    service: "3D & AR Experiences",
    description: "An immersive product page concept where configuration and context do the selling.",
    stack: "React · Three.js · WebGL",
    scope: "Selected experiment",
    image: siteImages.work3,
    gallery: [siteImages.work3, siteImages.hero, siteImages.work2],
  },
  {
    slug: "quiet-kitchen",
    number: "04",
    title: "Quiet Kitchen",
    category: "Food & Beverage",
    industry: "Food & Beverage",
    service: "Performance & SEO",
    description: "A calmer direct-to-consumer experience for pantry staples, built around repeat purchase and useful discovery.",
    stack: "Next.js · Shopify · Technical SEO",
    scope: "Selected experiment",
    image: siteImages.hero,
    gallery: [siteImages.hero, siteImages.work3, siteImages.work1],
  },
  {
    slug: "field-notes",
    number: "05",
    title: "Field Notes",
    category: "Outdoor",
    industry: "Outdoor",
    service: "Conversion & Recovery",
    description: "A commerce recovery concept that turns product education into a more confident return visit.",
    stack: "React · Shopify · Analytics",
    scope: "Selected experiment",
    image: siteImages.work2,
    gallery: [siteImages.work2, siteImages.work3, siteImages.hero],
  },
  {
    slug: "afterlight",
    number: "06",
    title: "Afterlight",
    category: "Home & Living",
    industry: "Home & Living",
    service: "Ongoing Development",
    description: "A modular release system for a growing home brand that needs every launch to feel considered.",
    stack: "Next.js · CMS · Design systems",
    scope: "Selected experiment",
    image: siteImages.work1,
    gallery: [siteImages.work1, siteImages.work2, siteImages.work3],
  },
  {
    slug: "aethelon-furniture-commerce",
    number: "07",
    title: "Aethelon",
    category: "Furniture",
    industry: "Furniture",
    service: "AI Commerce",
    description: "A self-directed luxury furniture commerce build that brings category browsing, AI-assisted discovery, and room-visualisation flows into one considered storefront.",
    stack: "Next.js · Prisma · AI commerce",
    scope: "Self-directed product build",
    image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663885080823/XjsnykjYkwELaHeZ.webp",
    gallery: [
      "https://files.manuscdn.com/user_upload_by_module/session_file/310519663885080823/XjsnykjYkwELaHeZ.webp",
      "https://files.manuscdn.com/user_upload_by_module/session_file/310519663885080823/aPkLvUvAoiaSCkBD.webp",
      "https://files.manuscdn.com/user_upload_by_module/session_file/310519663885080823/xWeXSMfDyBsJzucR.webp",
    ],
    build: "The source project brings an editorial furniture storefront together with category browsing, AI-assisted search, a room visualiser, a concierge interaction, and commerce route structure.",
    focus: "Discovery · AI flows · Commerce",
  },
  {
    slug: "novexa-product-commerce",
    number: "08",
    title: "Novexa",
    category: "Footwear",
    industry: "Footwear",
    service: "3D & AR Experiences",
    description: "A self-directed footwear commerce concept combining product discovery, an AI-stylist demonstration, 3D model delivery, and virtual try-on routes.",
    stack: "Next.js · Stripe · 3D product",
    scope: "Self-directed product build",
    image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663885080823/RrLVtFHOEYEZntFV.webp",
    gallery: [
      "https://files.manuscdn.com/user_upload_by_module/session_file/310519663885080823/RrLVtFHOEYEZntFV.webp",
      "https://files.manuscdn.com/user_upload_by_module/session_file/310519663885080823/kQIspgJCsnkbBQnL.webp",
      "https://files.manuscdn.com/user_upload_by_module/session_file/310519663885080823/VMzMkbifesChbmfA.webp",
    ],
    build: "The source project combines a storefront and checkout structure with AI-assistant endpoints, search, a 3D product module, virtual try-on routes, and payment or fulfillment integration surfaces.",
    focus: "3D product · Try-on · AI assistant",
  },
  {
    slug: "velorum-watch-commerce",
    number: "09",
    title: "Velorum",
    category: "Luxury Watches",
    industry: "Luxury Watches",
    service: "Custom E-commerce",
    description: "A self-directed luxury-watch commerce build with a 3D product viewer, intelligent search, concierge interactions, checkout, and operational dashboard routes.",
    stack: "Next.js · Three.js · Stripe",
    scope: "Self-directed product build",
    image: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663885080823/UXlwMQudKfmlPDQd.webp",
    gallery: [
      "https://files.manuscdn.com/user_upload_by_module/session_file/310519663885080823/UXlwMQudKfmlPDQd.webp",
      "https://files.manuscdn.com/user_upload_by_module/session_file/310519663885080823/WVOUBxzxptVDEabu.webp",
      "https://files.manuscdn.com/user_upload_by_module/session_file/310519663885080823/aUxAnUAHNdmxibML.webp",
    ],
    build: "The source project includes a watch-focused product system with 3D viewing components, search, an AI concierge, bag and checkout flows, and commerce-operations dashboard routes.",
    focus: "3D viewing · Search · Checkout",
  },
] as const;

export type Project = (typeof projects)[number];

export function getProject(slug: string) {
  return projects.find((project) => project.slug === slug);
}
